### ISSUE TITLE
Create a webhook POST

### ISSUE THREAD

**Issue by SaimonL** [Files-com/files-sdk-ruby#12]
Hi is there a way to use the API to create a webhook that uses the POST method.

I am looking at the documentation how ever not enough data for POST
https://developers.files.com/#create-behavior

Basically I want to automate webhook below:
<img width="368" alt="Screen Shot 2021-02-16 at 1 40 03 PM" src="https://user-images.githubusercontent.com/7557791/108106943-97bd4d80-705c-11eb-887b-43e6b69287d2.png">

I am making a wild guess below any help will be appriciated.
```ruby
Files::Behavior.create(
  url: 'https://example.com/webhooks/incoming',
  path: 'development/foo',
  value: { 
    method: :POST, 
    encoding: :JSON, 
    triggers: %w[create],
    headers: { 'api-key': 'some-super-secret' },
    body: { id: 1234 }
  }.to_json, 
  behavior: 'webhook'
)
```
Thank you.

**Comment by romcart** [comment]
Hello @SaimonL,

I'm sorry for the lack of more detailed code examples for creating webhook behaviors. We'll work on improving that.

Your code is very close. You just need to change `url` to `urls` (since a webhook can have multiple URL targets) and move it inside of `value`.

 ```ruby
Files::Behavior.create(
  path: 'development/foo',
  value: { 
    urls: ['https://example.com/webhooks/incoming'],
    method: :POST, 
    encoding: :JSON, 
    triggers: %w[create],
    headers: { 'api-key': 'some-super-secret' },
    body: { id: 1234 }
  }.to_json, 
  behavior: 'webhook'
)
```

That should do the trick, but please let us know if we can assist further. You can also reach us at support@files.com.

**Comment by SaimonL** [comment]
Thank you. You just saved me from making webhooks on 1,000 of folders
