### ISSUE TITLE
Files::Dir fails with undefined method exception

### ISSUE THREAD

**Issue by TJNII** [Files-com/files-sdk-ruby#3]
Attempting to follow the documentation and the `List using array syntax example` is failing with what appears to be an internal bug:

```ruby
[7] pry(main)> Files::Dir['/']
NoMethodError: undefined method `list' for Files::Folder:Class
from /home/tom/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/files.com-1.0.25/lib/files.com/models/folder.rb:58:in `find_recursive'
[8] pry(main)> 
```

```bash
$ gem list | grep files
files.com (1.0.25)
```

**Comment by fastjames** [comment]
Hello @TJNII I submitted a PR that I think addresses the error you encountered. I don't know if PRs are being accepted, but I wanted to document what I found in case you were still interested.

**Comment by zeisler** [comment]
Hi @TJNII  I apologize for the delay. Thank you for altering us of this issue. We have decided to remove our implementation of `Files::Dir[]` because of performance concerns with our API. The supported approach `#list_for` returns a folder at time, see [README](https://github.com/Files-com/files-sdk-ruby#list-root-folder).
